"""Modality-specific observation models.

Each emission model answers one question: given that the resident is in state
``z``, how surprising is what this sensor reported over the last interval?
Keeping that question per-sensor is what makes the fusion layer genuinely
multimodal -- modalities with different units, sampling rates and temporal
semantics each get an appropriate likelihood, and the filter combines them.

Two mechanisms are shared by every model.

*Tempering.* The raw log-likelihood is multiplied by the sensor's reliability
and by the probability that what it saw was generated by the monitored
resident. A reliability of zero contributes exactly nothing, which is the
formal statement of "a broken sensor is missing evidence, not evidence of
inactivity". This is a power-likelihood weighting in the sense of generalised
Bayesian updating, and it degrades smoothly rather than switching a sensor
abruptly on and off.

*Centring.* Log-likelihoods are shifted so the best-supported state sits at
zero. State-independent constants cancel under normalisation anyway, and
centring makes each model's output directly readable as "how much worse is
this state than the best one, according to this sensor".
"""

from __future__ import annotations

import math
from abc import ABC, abstractmethod
from collections.abc import Mapping, Sequence
from dataclasses import dataclass, field
from datetime import timedelta

import numpy as np

from ..observations.observation import Observation
from ..states.ontology import BehaviouralState, StateOntology

#: Smallest event rate any state may have, in events per second. A state that
#: "never" triggers a sensor still needs a positive rate, or a single spurious
#: activation would drive its posterior to exactly zero and make it
#: unrecoverable for the rest of the deployment.
MIN_RATE = 1e-9

#: Floor applied to Bernoulli and Beta parameters for the same reason.
EPSILON = 1e-6


@dataclass
class EmissionModel(ABC):
    """Base class for per-sensor observation models.

    Parameters
    ----------
    sensor_id
        Sensor this model interprets.
    weight
        Evidence weight for the modality. Fast-sampling sensors accumulate
        more log-likelihood per interval simply by reporting more often; this
        multiplier lets a deployment correct that imbalance deliberately
        rather than letting sampling rate decide how much a modality counts.
    """

    sensor_id: str
    weight: float = 1.0

    def __post_init__(self) -> None:
        """Validate shared configuration."""
        if not isinstance(self.sensor_id, str) or not self.sensor_id.strip():
            raise ValueError("sensor_id must be a non-empty string")
        if not math.isfinite(self.weight) or self.weight < 0.0:
            raise ValueError("weight must be finite and non-negative")

    @abstractmethod
    def _raw_log_likelihood(
        self,
        ontology: StateOntology,
        observations: Sequence[Observation],
        elapsed: timedelta,
    ) -> np.ndarray:
        """Return the untempered per-state log-likelihood."""

    def log_likelihood(
        self,
        ontology: StateOntology,
        observations: Sequence[Observation],
        elapsed: timedelta,
        *,
        reliability: float = 1.0,
        attribution: float = 1.0,
    ) -> np.ndarray:
        """Return the tempered, centred per-state log-likelihood.

        Parameters
        ----------
        reliability
            Health-derived evidence weight in ``[0, 1]``.
        attribution
            Probability in ``[0, 1]`` that the monitored resident generated
            what this sensor saw. Ambient sensors in a home with a visitor
            should pass a value below one.
        """
        temper = self.weight * float(reliability) * float(attribution)
        if temper <= 0.0:
            return np.zeros(ontology.size)
        raw = np.asarray(
            self._raw_log_likelihood(ontology, observations, elapsed), dtype=float
        )
        if raw.shape != (ontology.size,):
            raise ValueError("emission models must return one value per state")
        if not np.all(np.isfinite(raw)):
            raise ValueError(
                f"emission model for '{self.sensor_id}' produced non-finite values"
            )
        tempered: np.ndarray = temper * (raw - raw.max())
        return tempered

    @staticmethod
    def _per_state(
        ontology: StateOntology,
        values: Mapping[BehaviouralState, float],
        default: float,
    ) -> np.ndarray:
        """Expand a per-state mapping into a vector in ontology order."""
        return np.array(
            [float(values.get(state, default)) for state in ontology.states],
            dtype=float,
        )


@dataclass
class PoissonEventEmission(EmissionModel):
    """Event sensors modelled as a state-dependent Poisson process.

    Over an interval of length ``T`` in which ``n`` activations were recorded,
    a state with rate ``lambda`` has log-likelihood ``n log(lambda) -
    lambda * T`` up to a constant. This is the natural model for irregular
    event streams, and it handles the two hard cases correctly without
    special-casing:

    *Silence is graded evidence.* A long quiet interval penalises high-rate
    states in proportion to how long the silence lasted, rather than being
    treated as an observation of zero activity.

    *Asynchrony is free.* The likelihood depends on elapsed time, so events
    arriving at irregular moments need no resampling onto a grid.

    Parameters
    ----------
    rates
        Activations per hour expected in each state.
    default_rate
        Rate per hour for states not named in *rates*.
    """

    rates: Mapping[BehaviouralState, float] = field(default_factory=dict)
    default_rate: float = 0.05

    def __post_init__(self) -> None:
        """Validate the declared rates."""
        super().__post_init__()
        for state, rate in self.rates.items():
            if not math.isfinite(rate) or rate < 0.0:
                raise ValueError(f"rate for {state} must be finite and non-negative")
        if not math.isfinite(self.default_rate) or self.default_rate < 0.0:
            raise ValueError("default_rate must be finite and non-negative")

    def _raw_log_likelihood(
        self,
        ontology: StateOntology,
        observations: Sequence[Observation],
        elapsed: timedelta,
    ) -> np.ndarray:
        per_second = (
            np.maximum(self._per_state(ontology, self.rates, self.default_rate), 0.0)
            / 3600.0
        )
        per_second = np.maximum(per_second, MIN_RATE)
        count = sum(1 for obs in observations if obs.value != 0.0)
        duration = max(elapsed.total_seconds(), 0.0)
        loglik: np.ndarray = count * np.log(per_second) - per_second * duration
        return loglik


@dataclass
class GaussianEmission(EmissionModel):
    """Sampled scalar signals modelled as state-dependent Gaussians.

    Suitable for wearable activity counts, ambient light, or any continuously
    sampled quantity whose typical level differs between states.

    Parameters
    ----------
    means
        Expected value of the signal in each state.
    sigmas
        Standard deviation in each state.
    default_mean, default_sigma
        Values used for states not named explicitly.
    """

    means: Mapping[BehaviouralState, float] = field(default_factory=dict)
    sigmas: Mapping[BehaviouralState, float] = field(default_factory=dict)
    default_mean: float = 0.0
    default_sigma: float = 1.0

    def __post_init__(self) -> None:
        """Validate the declared moments."""
        super().__post_init__()
        if self.default_sigma <= 0.0 or not math.isfinite(self.default_sigma):
            raise ValueError("default_sigma must be positive and finite")
        for state, sigma in self.sigmas.items():
            if not math.isfinite(sigma) or sigma <= 0.0:
                raise ValueError(f"sigma for {state} must be positive and finite")

    def _raw_log_likelihood(
        self,
        ontology: StateOntology,
        observations: Sequence[Observation],
        elapsed: timedelta,
    ) -> np.ndarray:
        if not observations:
            return np.zeros(ontology.size)
        means = self._per_state(ontology, self.means, self.default_mean)
        sigmas = self._per_state(ontology, self.sigmas, self.default_sigma)
        values = np.array([obs.value for obs in observations], dtype=float)
        residuals = values[:, None] - means[None, :]
        loglik: np.ndarray = -(
            0.5 * (residuals / sigmas[None, :]) ** 2 + np.log(sigmas)[None, :]
        ).sum(axis=0)
        return loglik


@dataclass
class BernoulliEmission(EmissionModel):
    """Binary state sensors modelled as state-dependent Bernoulli draws.

    Suitable for bed or chair occupancy, where the sensor reports a level that
    persists until it changes. Only the most recent reading in the interval is
    used, because repeated reports of an unchanged state are not repeated
    independent measurements of it.

    Parameters
    ----------
    probabilities
        Probability the sensor reads one in each state.
    default_probability
        Probability for states not named explicitly.
    """

    probabilities: Mapping[BehaviouralState, float] = field(default_factory=dict)
    default_probability: float = 0.5

    def __post_init__(self) -> None:
        """Validate the declared probabilities."""
        super().__post_init__()
        values = [*self.probabilities.values(), self.default_probability]
        if any(not math.isfinite(p) or not 0.0 <= p <= 1.0 for p in values):
            raise ValueError("probabilities must lie in [0, 1]")

    def _raw_log_likelihood(
        self,
        ontology: StateOntology,
        observations: Sequence[Observation],
        elapsed: timedelta,
    ) -> np.ndarray:
        if not observations:
            return np.zeros(ontology.size)
        probabilities = np.clip(
            self._per_state(ontology, self.probabilities, self.default_probability),
            EPSILON,
            1.0 - EPSILON,
        )
        latest = observations[-1].value
        loglik: np.ndarray = (
            np.log(probabilities) if latest != 0.0 else np.log1p(-probabilities)
        )
        return loglik


@dataclass
class BetaEmission(EmissionModel):
    """Probability-valued derived features modelled as Beta draws.

    Radar and room-occupancy devices commonly report a presence probability
    rather than a raw measurement. Treating that number as a Beta observation
    keeps it on its natural support and lets the deployment state how much to
    trust it through the concentration parameter, instead of hard-thresholding
    it into a binary and discarding the uncertainty the device supplied.

    Parameters
    ----------
    means
        Expected feature value in each state, strictly inside ``(0, 1)``.
    concentration
        Beta concentration. Larger values mean the feature is expected to sit
        tightly around its state mean.
    default_mean
        Mean for states not named explicitly.
    """

    means: Mapping[BehaviouralState, float] = field(default_factory=dict)
    concentration: float = 8.0
    default_mean: float = 0.5

    def __post_init__(self) -> None:
        """Validate the declared means and concentration."""
        super().__post_init__()
        if not math.isfinite(self.concentration) or self.concentration <= 0.0:
            raise ValueError("concentration must be positive and finite")
        values = [*self.means.values(), self.default_mean]
        if any(not math.isfinite(m) or not 0.0 <= m <= 1.0 for m in values):
            raise ValueError("means must lie in [0, 1]")

    def _raw_log_likelihood(
        self,
        ontology: StateOntology,
        observations: Sequence[Observation],
        elapsed: timedelta,
    ) -> np.ndarray:
        if not observations:
            return np.zeros(ontology.size)
        means = np.clip(
            self._per_state(ontology, self.means, self.default_mean),
            EPSILON,
            1.0 - EPSILON,
        )
        alpha = self.concentration * means
        beta = self.concentration * (1.0 - means)
        values = np.clip(
            np.array([obs.value for obs in observations], dtype=float),
            EPSILON,
            1.0 - EPSILON,
        )
        log_values = np.log(values)[:, None]
        log_complements = np.log1p(-values)[:, None]
        loglik: np.ndarray = (
            (alpha - 1.0) * log_values + (beta - 1.0) * log_complements
        ).sum(axis=0)
        return loglik
