"""The output of multimodal fusion: a state belief with its justification.

A :class:`StateEstimate` is deliberately more than an argmax. It carries the
full posterior, how confident that posterior is, how much of the sensing
apparatus was actually contributing, which sensors supported the conclusion
and which contradicted it, and which supplied nothing at all.

It can also decline. When confidence is low or too little evidence was
available, :attr:`StateEstimate.state` is
:attr:`~sensor_modeling.states.BehaviouralState.UNKNOWN` -- an abstention,
not a prediction of an eighth behaviour.
"""

from __future__ import annotations

import math
from collections.abc import Mapping, Sequence
from dataclasses import dataclass
from datetime import datetime

import numpy as np

from ..observations.types import Modality
from ..states.ontology import BehaviouralState, StateOntology


@dataclass(frozen=True)
class EvidenceContribution:
    """What one sensor contributed to the conclusion.

    Attributes
    ----------
    sensor_id
        Sensor the contribution came from.
    modality
        Modality of that sensor.
    support
        Log-likelihood margin the sensor gives the winning state over the
        best alternative. Positive means the sensor favours the conclusion,
        negative means it favours something else, zero means it is
        indifferent between them.
    reliability
        Health-derived evidence weight applied to the sensor.
    attribution
        Probability that what the sensor saw was generated by the monitored
        resident rather than someone else.
    observations
        Number of records this sensor supplied over the interval.
    """

    sensor_id: str
    modality: Modality
    support: float
    reliability: float
    attribution: float
    observations: int

    @property
    def supports(self) -> bool:
        """Whether the sensor favours the reported state."""
        return self.support > 0.0

    @property
    def contradicts(self) -> bool:
        """Whether the sensor favours some other state."""
        return self.support < 0.0

    @property
    def reported(self) -> bool:
        """Whether the sensor produced any records over the interval."""
        return self.observations > 0

    @property
    def informative(self) -> bool:
        """Whether the sensor's likelihood was applied at all.

        A trusted event sensor that stayed quiet is still informative: under
        a Poisson observation model its silence actively penalises the
        states that would have triggered it. Only a sensor discounted to
        zero reliability contributes nothing.
        """
        return self.reliability > 0.0

    def to_dict(self) -> dict[str, object]:
        """Return a serialisable form of the contribution."""
        return {
            "sensor_id": self.sensor_id,
            "modality": self.modality.value,
            "support": self.support,
            "reliability": self.reliability,
            "attribution": self.attribution,
            "observations": self.observations,
        }


@dataclass(frozen=True)
class StateEstimate:
    """A posterior over latent behavioural states, with its justification."""

    at: datetime
    ontology: StateOntology
    belief: np.ndarray
    evidence: tuple[EvidenceContribution, ...]
    completeness: float
    min_confidence: float
    min_completeness: float

    def __post_init__(self) -> None:
        """Validate the belief vector."""
        belief = np.asarray(self.belief, dtype=float)
        if belief.shape != (self.ontology.size,):
            raise ValueError("belief must have one entry per ontology state")
        if not np.all(np.isfinite(belief)) or belief.min() < 0.0:
            raise ValueError("belief must be finite and non-negative")
        total = belief.sum()
        if total <= 0.0:
            raise ValueError("belief must contain at least some probability mass")
        object.__setattr__(self, "belief", belief / total)

    # ------------------------------------------------------------------
    @property
    def probabilities(self) -> dict[BehaviouralState, float]:
        """Posterior probability of each latent state."""
        return dict(zip(self.ontology.states, (float(p) for p in self.belief)))

    @property
    def most_likely(self) -> BehaviouralState:
        """The highest-posterior state, regardless of whether it is credible."""
        return self.ontology.states[int(np.argmax(self.belief))]

    @property
    def confidence(self) -> float:
        """Posterior mass on the most likely state."""
        return float(self.belief.max())

    @property
    def margin(self) -> float:
        """Gap between the two highest posterior probabilities."""
        if self.belief.size < 2:
            return self.confidence
        ordered = np.sort(self.belief)
        return float(ordered[-1] - ordered[-2])

    @property
    def entropy(self) -> float:
        """Shannon entropy of the posterior in nats."""
        mass = self.belief[self.belief > 0.0]
        return float(-(mass * np.log(mass)).sum())

    @property
    def normalised_entropy(self) -> float:
        """Entropy scaled to ``[0, 1]``; one means completely undecided."""
        if self.ontology.size < 2:
            return 0.0
        return self.entropy / math.log(self.ontology.size)

    @property
    def abstained(self) -> bool:
        """Whether the estimate declines to name a state.

        Two independent reasons force an abstention: the posterior is too
        flat to justify a claim, or too little of the sensing apparatus was
        contributing for any posterior to be trustworthy.
        """
        return (
            self.confidence < self.min_confidence
            or self.completeness < self.min_completeness
        )

    @property
    def state(self) -> BehaviouralState:
        """The reported state, or ``UNKNOWN`` when the estimate abstains."""
        return BehaviouralState.UNKNOWN if self.abstained else self.most_likely

    # ------------------------------------------------------------------
    @property
    def supporting(self) -> tuple[EvidenceContribution, ...]:
        """Sensors favouring the most likely state, strongest first."""
        return tuple(
            sorted(
                (c for c in self.evidence if c.supports),
                key=lambda c: c.support,
                reverse=True,
            )
        )

    @property
    def contradicting(self) -> tuple[EvidenceContribution, ...]:
        """Sensors favouring some other state, strongest first."""
        return tuple(
            sorted((c for c in self.evidence if c.contradicts), key=lambda c: c.support)
        )

    @property
    def missing(self) -> tuple[str, ...]:
        """Sensors discounted to zero reliability, contributing nothing."""
        return tuple(c.sensor_id for c in self.evidence if not c.informative)

    @property
    def silent(self) -> tuple[str, ...]:
        """Trusted sensors that reported nothing over the interval.

        Their silence still informed the posterior; this is a record of what
        was quiet, not of what was broken.
        """
        return tuple(
            c.sensor_id for c in self.evidence if c.informative and not c.reported
        )

    def explain(self, limit: int = 3) -> str:
        """Return a short human-readable justification for the estimate.

        The wording is intentionally cautious. It reports what the sensors
        indicated and how confident the model is, and makes no clinical claim.
        """
        if self.abstained:
            reason = (
                "insufficient sensor coverage"
                if self.completeness < self.min_completeness
                else "no state was clearly indicated"
            )
            return (
                f"State unknown at {self.at.isoformat()}: {reason} "
                f"(confidence {self.confidence:.2f}, "
                f"coverage {self.completeness:.2f})."
            )

        parts = [
            f"{self.state.value} at {self.at.isoformat()} "
            f"with probability {self.confidence:.2f}"
        ]
        supporting = self.supporting[:limit]
        if supporting:
            named = ", ".join(f"{c.sensor_id} (+{c.support:.2f})" for c in supporting)
            parts.append(f"supported by {named}")
        contradicting = self.contradicting[:limit]
        if contradicting:
            named = ", ".join(f"{c.sensor_id} ({c.support:.2f})" for c in contradicting)
            parts.append(f"contradicted by {named}")
        if self.missing:
            parts.append(f"no evidence from {', '.join(self.missing)}")
        if self.silent:
            parts.append(f"nothing reported by {', '.join(self.silent)}")
        return "; ".join(parts) + "."

    def to_dict(self) -> dict[str, object]:
        """Return a serialisable form of the estimate."""
        return {
            "at": self.at.isoformat(),
            "state": self.state.value,
            "most_likely": self.most_likely.value,
            "abstained": self.abstained,
            "confidence": self.confidence,
            "margin": self.margin,
            "normalised_entropy": self.normalised_entropy,
            "completeness": self.completeness,
            "probabilities": {
                state.value: probability
                for state, probability in self.probabilities.items()
            },
            "evidence": [c.to_dict() for c in self.evidence],
            "missing": list(self.missing),
            "silent": list(self.silent),
            "explanation": self.explain(),
        }


def belief_from_mapping(
    ontology: StateOntology, probabilities: Mapping[BehaviouralState, float]
) -> np.ndarray:
    """Build a belief vector from a mapping, filling absent states with zero."""
    return np.array(
        [float(probabilities.get(state, 0.0)) for state in ontology.states], dtype=float
    )


def belief_matrix(estimates: Sequence[StateEstimate]) -> np.ndarray:
    """Stack the beliefs of several estimates into a ``(n, n_states)`` array."""
    if not estimates:
        return np.zeros((0, 0))
    return np.vstack([estimate.belief for estimate in estimates])
